
project_id = "jbkybxwxnhwokqtvfcoq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
inmemory = false

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true

[realtime]
enabled = true

[functions]
[functions.order-helpers]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false
