// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keqjreynlkakvnbhmapq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcWpyZXlubGtha3ZuYmhtYXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzcyMzYsImV4cCI6MjA2Mzk1MzIzNn0.-zNG5fmGc4IxK77a1-oP1DAcvUj9u0yMqPavqysUy0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);