
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbkybxwxnhwokqtvfcoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impia3lieHd4bmh3b2txdHZmY29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzMzMDEsImV4cCI6MjA2MDcwOTMwMX0.5K8Y7J3V2RpqKD_Yq_OohvaE7YlR0jPrIfzXFj-etlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: (url, options) => fetch(url, options),
    },
  }
);
